# Generated by Django 2.1.3 on 2018-11-22 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curp', models.CharField(max_length=18)),
                ('nombre', models.CharField(max_length=255)),
                ('apellidop', models.CharField(max_length=255)),
                ('apellidom', models.CharField(max_length=255)),
                ('sexo', models.CharField(choices=[('m', 'Mujer'), ('h', 'Hombre')], max_length=1)),
                ('parentesco', models.CharField(choices=[('padre', 'Padre'), ('madre', 'Madre'), ('hijo', 'Hijo(a)'), ('nieto', 'Nieto(a)'), ('hermano', 'Hermano(a)'), ('abuelo', 'Abuelo(a)'), ('tio', 'Tio(a)'), ('primo', 'Primo(a)')], max_length=255)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Empleado')),
            ],
        ),
    ]
