# Generated by Django 2.1.3 on 2018-11-22 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_familiar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('estatus', models.CharField(choices=[('1', 'Disponible'), ('2', 'Ocupado')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Departamento')),
            ],
        ),
        migrations.AlterField(
            model_name='familiar',
            name='parentesco',
            field=models.CharField(choices=[('padre', 'Padre'), ('madre', 'Madre'), ('hijo', 'Hijo(a)'), ('nieto', 'Nieto(a)'), ('hermano', 'Hermano(a)'), ('abuelo', 'Abuelo(a)'), ('tio', 'Tio(a)'), ('primo', 'Primo(a)'), ('otro', 'Otro')], max_length=255),
        ),
    ]
