# Generated by Django 2.1.3 on 2018-11-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181122_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='issupervisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='parentesco',
            field=models.CharField(choices=[('padre', 'Padre'), ('madre', 'Madre'), ('hijo', 'Hijo(a)'), ('esposo', 'Esposo(a)'), ('nieto', 'Nieto(a)'), ('hermano', 'Hermano(a)'), ('abuelo', 'Abuelo(a)'), ('tio', 'Tio(a)'), ('primo', 'Primo(a)'), ('otro', 'Otro')], max_length=255),
        ),
    ]
