# Generated by Django 2.1.3 on 2018-11-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181126_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masignada',
            name='estatus',
            field=models.CharField(choices=[('1', 'Disponible'), ('2', 'Ocupado')], default='1', max_length=255),
        ),
        migrations.AlterField(
            model_name='masignada',
            name='fechaa',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='masignada',
            name='fechae',
            field=models.DateField(blank=True, null=True),
        ),
    ]
